import type { ReportKind, StoreIntelligence } from './types';

function fmt(currency: string, n: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(n);
}

export function generateBusinessReport(
  kind: ReportKind,
  intel: StoreIntelligence,
  currency: string,
  storeName: string,
): string {
  const lines: string[] = [];
  const divider = '─'.repeat(40);
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  lines.push(`KULMIS ERP — ${storeName}`);
  lines.push(`${reportTitle(kind)} · ${date}`);
  lines.push(divider);

  switch (kind) {
    case 'daily':
      lines.push(`Today's Sales: ${fmt(currency, intel.briefing.summary.sales)}`);
      lines.push(`Today's Profit: ${fmt(currency, intel.briefing.summary.profit)}`);
      lines.push(`Today's Expenses: ${fmt(currency, intel.briefing.summary.expenses)}`);
      lines.push(`Transactions: ${intel.briefing.summary.transactionCount}`);
      lines.push(`New Customers: ${intel.briefing.summary.newCustomers}`);
      if (intel.topProducts[0]) {
        lines.push(`Top Product: ${intel.topProducts[0].name} (${fmt(currency, intel.topProducts[0].revenue)})`);
      }
      break;

    case 'weekly':
    case 'monthly':
      lines.push(`Revenue (MTD): ${fmt(currency, intel.metrics.monthRevenue)}`);
      lines.push(`Expenses (MTD): ${fmt(currency, intel.metrics.monthExpenses)}`);
      lines.push(`Net Profit (MTD): ${fmt(currency, intel.metrics.monthProfit)}`);
      if (intel.metrics.growthRate !== null) {
        lines.push(`Growth vs Last Month: ${intel.metrics.growthRate >= 0 ? '+' : ''}${intel.metrics.growthRate}%`);
      }
      lines.push(`Cash Balance: ${fmt(currency, intel.metrics.cashBalance)}`);
      lines.push('');
      lines.push('Top Products:');
      intel.topProducts.slice(0, 5).forEach((p, i) => {
        lines.push(`  ${i + 1}. ${p.name} — ${fmt(currency, p.revenue)} (${p.quantity} sold)`);
      });
      break;

    case 'inventory':
      lines.push(`Inventory Value: ${fmt(currency, intel.metrics.inventoryValue)}`);
      lines.push(`Low Stock Items: ${intel.lowStockProducts.length}`);
      intel.lowStockProducts.slice(0, 8).forEach((p) => {
        lines.push(`  • ${p.name}: ${p.stock} left (min ${p.minLevel})`);
      });
      lines.push('');
      lines.push('Reorder Recommendations:');
      intel.forecasts.slice(0, 5).forEach((f) => {
        lines.push(
          `  • ${f.name}: ~${f.daysUntilStockout ?? '?'} days left, suggest ${Math.ceil(f.suggestedReorderQty)} units`,
        );
      });
      break;

    case 'debt':
      lines.push(`Total Receivables: ${fmt(currency, intel.metrics.receivables)}`);
      lines.push(`Payables: ${fmt(currency, intel.metrics.payables)}`);
      lines.push(`Customers with Balance: ${intel.debtSummary.customersWithBalance}`);
      lines.push(`Overdue Records: ${intel.debtSummary.overdueCount}`);
      lines.push('');
      lines.push('Top Debtors:');
      intel.debtSummary.topDebtors.forEach((d) => {
        lines.push(`  • ${d.name}: ${fmt(currency, d.balance)}`);
      });
      break;

    case 'profit':
      lines.push(`Month Revenue: ${fmt(currency, intel.metrics.monthRevenue)}`);
      lines.push(`Month Expenses: ${fmt(currency, intel.metrics.monthExpenses)}`);
      lines.push(`Net Profit: ${fmt(currency, intel.metrics.monthProfit)}`);
      lines.push(
        `Profit Margin: ${
          intel.metrics.monthRevenue > 0
            ? `${Math.round((intel.metrics.monthProfit / intel.metrics.monthRevenue) * 100)}%`
            : 'N/A'
        }`,
      );
      lines.push(`Today's Profit: ${fmt(currency, intel.briefing.summary.profit)}`);
      break;

    case 'health':
      lines.push(`Business Health Score: ${intel.health.score}/100 (${intel.health.status})`);
      lines.push('');
      lines.push('Health Factors:');
      intel.health.factors.forEach((f) => {
        lines.push(`  • ${f.label}: ${Math.round(f.score)}/100`);
      });
      lines.push('');
      lines.push('Recommendations:');
      intel.briefing.recommendations.forEach((r) => lines.push(`  • ${r}`));
      break;
  }

  lines.push(divider);
  lines.push('Generated by KULMIS AI Copilot');
  return lines.join('\n');
}

function reportTitle(kind: ReportKind): string {
  const titles: Record<ReportKind, string> = {
    daily: 'Daily Business Report',
    weekly: 'Weekly Business Report',
    monthly: 'Monthly Business Report',
    inventory: 'Inventory Report',
    debt: 'Debt & Receivables Report',
    profit: 'Profit Report',
    health: 'Business Health Report',
  };
  return titles[kind];
}

export function reportKindFromQuery(query: string): ReportKind | null {
  const q = query.toLowerCase();
  if (/daily|today/.test(q) && /report/.test(q)) return 'daily';
  if (/weekly|week/.test(q) && /report/.test(q)) return 'weekly';
  if (/monthly|month/.test(q) && /report/.test(q)) return 'monthly';
  if (/inventory/.test(q) && /report/.test(q)) return 'inventory';
  if (/debt/.test(q) && /report/.test(q)) return 'debt';
  if (/profit/.test(q) && /report/.test(q)) return 'profit';
  return null;
}
